version: "3.8"
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      # Add your backend environment variables here, or use an env_file
    networks:
      - appnet

  frontend:
    build:
      context: ./Assignment
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
